### ISSUE TITLE
Client Doesn't Support Spaces in Classpath

### ISSUE THREAD

**Issue by rnielsen** [ldaley/remote-control#2]
If any of the entries in the classpath of the client have a space in it, groovy-remote in client mode fails with

```
java.util.zip.ZipException: error in opening zip file
at java.util.zip.ZipFile.open(Native Method)
at java.util.zip.ZipFile.<init>(ZipFile.java:114)
at java.util.zip.ZipFile.<init>(ZipFile.java:131)
at sun.reflect.GeneratedConstructorAccessor3.newInstance(Unknown Source)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:77)
at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:102)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:198)
at InnerClosureClassDefinitionsFinder.find(InnerClosureClassDefinitionsFinder.groovy:32)
at InnerClosureClassDefinitionsFinder$find.call(Unknown Source)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:40)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:124)
```

This is due to InnerClosureClassDefinitionsFinder using def root = new File(url.path) which leaves %20's in the name.  Changing to

root = new File(url.toURI())

seems to fix it.   This issue was manifesting itself as not being able to run tests containing groovy-remote (or grails-remote-control) code in Intellij IDEA as Intellij was including it's own jars when running the test and the path to my installation of IntelliJ includes spaces.

**Comment by ldaley** [comment]
Have patched and upload a new 0.2-SNAPSHOT.

If you want to try it out you can add it as a dependency in BuildConfig.groovy and it should evict the 0.1 version.

You'll need to add the following maven repo:

https://nexus.codehaus.org/content/repositories/snapshots/

**Comment by rnielsen** [comment]
Thanks.  That seems to resolve the issue.  Any idea when a non snapshot release will be available?  https://nexus.codehaus.org/content/repositories/snapshots/ isn't currently mapped through the corporate Nexus at work (although http://snapshots.repository.codehaus.org/ is).

**Comment by ldaley** [comment]
Will do a release tomorrow morning.
